spring:
  datasource:
    url: jdbc:h2:mem:sdw2025
    username: sdw2025
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
